### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by dylan-k** [real-pants/Real-Pants#1]
This is a meta issue. We can use this item's thread to discuss how to use github to track our todos, general questions and conversation, etc.

**Comment by dylan-k** [comment]
#77 has undergone a lycanthropic transformation, and, as we'd have it in the intro of a comic book, the world as we know it may never be the same again...

**Comment by dylan-k** [comment]
I've created [a separate branch](http://nvie.com/posts/a-successful-git-branching-model/) in the github project called 'develop'. I'll use this branch for tracking work-in-progress versions of the theme. You can browse it if you like at https://github.com/real-pants/Real-Pants/tree/develop

When the development is done, hopefully in just a few more days, the 'develop' branch can be merged into the 'master' branch, the theme can be published for all to see, and we'll happily arrive at version 1.2!

**Comment by dylan-k** [comment]
I'm pretty sure that I've finished building v1.2. I'll try to pick some off-hours this weekend or early next week to launch it on the site. There may be some rough spots related to widgets, their settings and placements, as I mentioned, but I'll try to minimize those. I'll check off the remaining issues related to that version as I've confirmed their fixes.

Let's do some cleanup of the issues while we're at it? Is there anything that can be closed? Anything that needs clarification or prioritization?

As the initial development of the site begins to slow, we should talk about a release schedule for subsequent builds. Maybe quarterly? I'm fixin' to take the summer off from web development, as much as possible.

**Comment by realpants** [comment]
I'm sorry about the widget confusion -- that was me removing a Twitter feed
and then not adding anything else (in the Inner Loop). Looking forward to
1.2 -- what are the big things, if any, that are being updated?

I'm cleaning up issues now.
