### ISSUE TITLE
Facebook Share Can Have Incorrect Byline

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#31]
![screen shot 2014-12-11 at 5 43 35 pm](https://cloud.githubusercontent.com/assets/10034861/5403745/64eeee62-815d-11e4-915b-44ce9426f359.png)
Just saw on Facebook that the site design is being credited to Designmodo -- Dylan, you should put yourself in that spot (or remove it, I don't see this on Facebook when other sites are linked).

**Comment by dylan-k** [comment]
This bug is alive again in another form so I'm reopening this. Whenever you share a link to the homepage, Facebook grabs the author of the first post.  It seems to work as intended for individual posts, though.

**Comment by dylan-k** [comment]
I've put a potential fix in place, and have notified Facebook to update its cache. We should know if that worked in about a day or so?

**Comment by dylan-k** [comment]
Closing this because the real issue is #64
