### ISSUE TITLE
Date field doesn't show up

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#59]
It appears on the first post, but the date isn't on the others.

**Comment by dylan-k** [comment]
This appears to occur only on the home page's index. The archives, like category and author, do not appear to be affected by this. Strangely, it doesn't seem to be a simple case where dates appear on the first post but not on the subsequent posts. I'm seeing dates on some of the subsequent posts too. I'm looking into it, but...

is there anything you know of that's special or different about the posts whose dates do appear, as opposed to the posts whose dates do not? Were they perhaps created differently somehow?

**Comment by dylan-k** [comment]
There's a special note in the docs for the date function that helps to illuminate this issue: http://codex.wordpress.org/Template_Tags/the_date

It occurs on posts that were published on the same day. The first post that day will have a date, the subsequent ones will not, unless you modify the function.

**Comment by realpants** [comment]
The only thing I can think is that they were edited after being published,
and maybe the others weren't? Other than that, I don't think there is one
particular thing different about how they were all posted.
