### ISSUE TITLE
Use "Fancier Author Bio" plugin for author bio on archive pages

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#62]

**Comment by dylan-k** [comment]
The plugin author says that [the plugin doesn't allow this functionality](https://wordpress.org/support/topic/adding-fancier-author-box-using-template-tag?replies=2) but says that there's another very similar plugin that does. Should we switch?

**Comment by realpants** [comment]
I'm okay with switching!

**Comment by dylan-k** [comment]
ok I think the one that will work best (of the free options) is [startbox](https://wordpress.org/plugins/starbox/). I'll do a trial run of it now, but it may mean that part of the site could look funny for a little minute.
