### ISSUE TITLE
Move sidebar to right?

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#70]
A few people have requested we move the sidebar to the right. I did a lot of reading on the issue, and there's no clear winner on which is better. One compelling argument for the right sidebar is that the eye reads from L -> R, so it's best not to have distraction at the left edge. An argument on the other side says, because of that same L -> R eye movement, left sidebars get more attention.

I made this mockup of what it would look like, and I think I like it. And since this is what most of the feedback I've received is about, I would like to try it. Is it hard? Or is it just a matter of moving a couple lines of code? 

Another factor is the repetition of Real Pants from the menu to the sidebar title. If the sidebar was on the right, they wouldn't be right below each other.

![right sidebar](https://cloud.githubusercontent.com/assets/10034861/5762590/0de6a780-9cb1-11e4-8394-ad26734b64b0.jpg)

**Comment by dylan-k** [comment]
While we're redesigning the sidebar can we also find a better way to stack the ads? Those wider ads that live in the sidebar, they cause an abundance of negative space for all of the sidebar that lies below them. Perhaps it's a matter of moving the wider ones to another location in the design?

**Comment by realpants** [comment]
I agree. I'm not sure what the solution is for this, but also recognize the problem. I was thinking about making the skyscraper ad the same width as the rectangles (300px). I will probably be talking to Litbreaker this month, and they might have some thoughts.
