### ISSUE TITLE
Search function doesn't work.

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#71]

**Comment by dylan-k** [comment]
Just some notes: there's no error displayed but the results are not right.
the search is showing what appears to be all posts, rather than the
filtered posts, relevant to the search query.

**Comment by dylan-k** [comment]
I believe this is fixed now. Please test the search for yourself and if you agree that it's fixed, close this issue. If it's not fixed, let me know if you see anything funny?
