### ISSUE TITLE
New sidebar design & related

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#78]
As referenced in issue #70 I have redesigned the general sidebar. Here are the things I'm going for in this sketch:

1. I deleted the Real Pants banner and would like to create a type logo that will fit in the main menu (this is exemplified in the script typeface I placed in the menu here, though this is not what I envision for the logo -- which will also be on the left side of the menu).
2. The widget title type should be san serif and 75% the current size
3. Can you control the type in the "Must Read" plugin to make the type size and color close to what I have here (in the first instance; the second two are unchanged)? I also changed this from 4 items to 3, but that is something I can manage in the Widget controls.
4. I'm also going to kill the skyscraper ad size. Lots of sites don't have this, even w/ Litbreaker.
5. The entire sidebar should be moved to the right.
6. I would like to remove the faint gray lines between widget areas.
7. I would like the type model as referenced here in point 3 to carry out in any subsequent widgets that we implement (such as the mailchimp sign up, which isn't shown here because it will be below the fold).

![sidebar-mockup](https://cloud.githubusercontent.com/assets/10034861/6321676/4ea80780-bad1-11e4-8a0b-db85f71b1c30.png)

**Comment by dylan-k** [comment]
Can you share or have you uploaded to the media library the type logo that will fit in the topnav?

**Comment by realpants** [comment]
I don't have one yet ... I guess I need to know the dimensions first.

**Comment by dylan-k** [comment]
The site should probably make use of the excerpts field for at least the most popular posts, since these would display both on the sidebar and on social media to get people interested reading the posts. For now the sidebar can grab the first few words of the post.

**Comment by realpants** [comment]
Agreed. I'll monitor the most popular posts and input excerpts (and I'll
get Bob to help me with this).
