### ISSUE TITLE
Next/Previous by category

### ISSUE THREAD

**Issue by realpants** [real-pants/Real-Pants#79]
Edward Mullany just pointed out that readers who start his series, "Rachel & Ben," at Episode 1, cannot easily navigate to Episode 2 and from 2 to 3, and so on. They have to go to the Archives each time.

I think what we need is a "Next/Previous Post" function that allow you to move only through particular categories. 

Is that possible? I have it in place at www.publishinggenius.com, but that was a theme option.

**Comment by dylan-k** [comment]
He's also pointed out the difficulty involved for him with the creation of the links, checking them, maintaining them, etc. so I agree that this enhancement would improve the usability, not just for the readers but also for the author.

**Comment by realpants** [comment]
Does this help? http://chriswharton.me/2014/03/category-based-previous-and-next-links-on-custom-post-types-for-wordpress/

**Comment by dylan-k** [comment]
@realpants, with the new next/previous functionality from the plugin, is this a closed issue or is the plugin a temporary measure?

**Comment by realpants** [comment]
I think you can close it, thanks!
