### ISSUE TITLE
"InnerLoop" Widget Settings Lost

### ISSUE THREAD

**Issue by dylan-k** [real-pants/Real-Pants#82]
While investigating #81 I have inadvertently removed the widget that was placed in the widget area called "InnerLoop". @realpants, could you replace it? 

It might also help to make a note of which widgets belong in which areas. While I'm building v1.2 these could get misplaced again, but I can easily reset them if I know what goes where.

If there are any unused widgets, is it safe to remove/uninstall/delete them?

**Comment by realpants** [comment]
Actually, I had removed the widget -- I wasn't happy with the recent comments showing there, bc it highlighted that there weren't many comments. I put the twitter feed there, but it doesn't work well on mobile. 

I'm not sure what the widget area would be best used for, at this point.

What do you mean by "unused widgets"?

**Comment by dylan-k** [comment]
If there are settings for a widget saved in the wordpress admin, but that widget is not (intended to be) displayed on the website, or it there is anything installed in order to provide a widget that is not displayed on the website, then I would call that an "unused widget" and I suppose it would be safe to remove.
